services:
  caddy:
    container_name: lubao-caddy
    image: caddy:latest
    restart: always
    networks:
      - lubao-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - ./assets:/var/lib/assets
  backend:
    container_name: lubao-backend
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: lubao-backend:py3.11
    restart: always
    networks:
      - lubao-network
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=lubao
      - POSTGRES_PASSWD=kiJ8v6PNykQqW9V8
      - POSTGRES_DB=lubao
    volumes:
      - ./assets:/app/assets
    depends_on:
      - postgresql
  postgresql:
    container_name: lubao-postgresql
    image: postgres:latest
    networks:
      - lubao-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lubao
      - POSTGRES_PASSWORD=kiJ8v6PNykQqW9V8
      - POSTGRES_DB=lubao
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  lubao-network:
    driver: bridge
